### ISSUE TITLE
Could not install pyzmail in python 3.6

### ISSUE THREAD

**Issue by limouren** [SkygearIO/forgot_password#13]
```sh
$ python --version
Python 3.6.0
$ pip install -r requirements.txt 
Collecting Jinja2==2.8 (from -r requirements.txt (line 1))
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting MarkupSafe==0.23 (from -r requirements.txt (line 2))
  Using cached MarkupSafe-0.23.tar.gz
Collecting pyzmail==1.0.3 (from -r requirements.txt (line 3))
  Using cached pyzmail-1.0.3.tar.gz
Collecting distribute (from pyzmail==1.0.3->-r requirements.txt (line 3))
  Using cached distribute-0.7.3.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hq/cgb7547x1l38kx3sn0rb2rjr0000gn/T/pip-build-ngbux7jr/distribute/
```

**Comment by limouren** [comment]
Shouldn't we get rid of pyzmail? It looks abandoned.

**Comment by limouren** [comment]
It works on python 3.5.3.

**Comment by cheungpat** [comment]
@limouren does `pyzmail36` works in both python 3.5.3 and python 3.6?

**Comment by cheungpat** [comment]
Thanks @limouren

**Comment by cheungpat** [comment]
fixed in #15
